services:
  cad-archives:
    build: .
    container_name: cad-archives
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - .:/uploads:/app/uploads
      - ./data:/app/data